# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Rcpp function
#' @name rwMetropolis
#' @description an Rcpp function for Exercise 9.4 (page 277, Statistical Computing with R)
#' @param sigma standard deviation
#' @param x0 original value
#' @param N length
#' @return generated random numbers \code{x}
#' @examples
#' \dontrun{
#' sd=2
#' x0=25
#' N = 2000
#' rwMetropolis(sigma,x0,N)
#' }
#' @export
rwMetropolis <- function(sigma, x0, N) {
    .Call('_StatComp20049_rwMetropolis', PACKAGE = 'StatComp20049', sigma, x0, N)
}

